spring:
  profiles:
    active: docker
    include: default
  datasource:
    url: jdbc:postgresql://satisfyer_postgres:5432/satisfyer_admin_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:RiLi9ohx@discovery-service:8061/eureka/