spring:
  profiles:
    active: docker
    include: default
  data:
    mongodb:
      uri: mongodb://admin:RiLi9ohx@satisfyer_mongo:27018/?authMechanism=SCRAM-SHA-1
      database: satisfyer_community_share_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:RiLi9ohx@discovery-service:8061/eureka/