server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:RiLi9ohx@localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: http://localhost:8091
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: http://localhost:8092
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: http://localhost:8093
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: chat-service-ws
          uri: ws://localhost:8094
          predicates:
            - Path=/chat-ws/**
          filters:
            - StripPrefix=1
        - id: chat-service-rest
          uri: http://localhost:8094
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
        - id: community-share-service
          uri: http://localhost:8095
          predicates:
            - Path=/community-share/**
          filters:
            - StripPrefix=1


satisfyerapp:
  authentication:
    jwt:
      xauthTokenHeaderName: x-auth-token
      secret: my-secret-token-to-change-in-production
      # Token is valid 24 hours
      tokenValidityInSeconds: 86400
      tokenValidityInSecondsForRememberMe: 2592000
